"use client";
/* eslint-disable @typescript-eslint/no-explicit-any */
import {useEffect,useMemo,useState} from "react";
import {BarChart3,Box,ClipboardList,Download,Film,ImagePlus,LayoutDashboard,LogOut,Package,Plus,Printer,ShoppingCart,Trash2,Truck,Upload,Users,X} from "lucide-react";
import {defaults,MakingVideo,Product} from "../storefront";

const menu=[[LayoutDashboard,"Overview"],[Package,"Products"],[ImagePlus,"Category Photos"],[Film,"Making Videos"],[ShoppingCart,"Orders"],[ClipboardList,"Custom Quotes"],[Users,"Customers"],[BarChart3,"Analytics"]] as const;
const imageUrl=(key:string)=>`/api/product-images?key=${encodeURIComponent(key)}`;
const money=(n:number)=>`₹${Number(n||0).toLocaleString("en-IN")}`;
const statuses=["new","accepted","processing","shipped","completed","cancelled"];
const categoryNames=["Bathroom","Kitchen","Home Organization","Desk & Office","Planters & Décor","Personalized Gifts"];

export default function AdminDashboard({owner,signOut}:{owner:string;signOut:string}){
 const [products,setProducts]=useState<Product[]>(defaults),[orders,setOrders]=useState<any[]>([]),[quotes,setQuotes]=useState<any[]>([]),[categoryPhotos,setCategoryPhotos]=useState<Record<string,string>>({}),[makingVideos,setMakingVideos]=useState<MakingVideo[]>([]),[videoSaving,setVideoSaving]=useState(false),[videoError,setVideoError]=useState(""),[categorySaving,setCategorySaving]=useState(""),[tab,setTab]=useState("Overview"),[editing,setEditing]=useState<Product|null>(null),[retainedKeys,setRetainedKeys]=useState<string[]>([]),[pendingFiles,setPendingFiles]=useState<{file:File;url:string}[]>([]),[saving,setSaving]=useState(false),[error,setError]=useState(""),[selectedOrder,setSelectedOrder]=useState<any|null>(null);
 useEffect(()=>{Promise.all([fetch("/api/products").then(r=>r.json()),fetch("/api/orders").then(r=>r.json()),fetch("/api/quotes").then(r=>r.json()),fetch("/api/categories").then(r=>r.json()),fetch("/api/videos").then(r=>r.json())]).then(([p,o,q,c,v])=>{if(p.products?.length)setProducts(p.products);setOrders(o.orders||[]);setQuotes(q.quotes||[]);setCategoryPhotos(Object.fromEntries((c.categories||[]).filter((x:any)=>x.imageKey).map((x:any)=>[x.name,x.imageKey])));setMakingVideos(v.videos||[])}).catch(()=>{})},[]);
 const sales=orders.filter(o=>o.orderStatus!=="cancelled").reduce((s,o)=>s+o.total,0),openOrders=orders.filter(o=>!["completed","cancelled"].includes(o.orderStatus)).length;
 const customers=useMemo(()=>Array.from(new Map(orders.map(o=>[o.phone,o])).values()),[orders]);
 const keysFor=(p:Product)=>p.imageKeys?.length?p.imageKeys:p.imageKey?[p.imageKey]:[];
 function openProduct(p:Product){setEditing(p);setRetainedKeys(keysFor(p));setPendingFiles([]);setError("")}
 function chooseImages(e:React.ChangeEvent<HTMLInputElement>){const files=Array.from(e.target.files||[]);setPendingFiles(c=>[...c,...files.map(file=>({file,url:URL.createObjectURL(file)}))]);e.target.value=""}
 function removePending(i:number){setPendingFiles(c=>{URL.revokeObjectURL(c[i].url);return c.filter((_,x)=>x!==i)})}
 async function saveCategoryPhoto(name:string,file:File){setCategorySaving(name);try{const form=new FormData();form.set("image",file);form.set("folder","categories");const upload=await fetch("/api/product-images",{method:"POST",body:form}),uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error||"Image upload failed");const save=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,imageKey:uploaded.key})}),saved=await save.json();if(!save.ok)throw new Error(saved.error||"Unable to save category photo");const previous=categoryPhotos[name];setCategoryPhotos(current=>({...current,[name]:uploaded.key}));if(previous)await fetch(`/api/product-images?key=${encodeURIComponent(previous)}`,{method:"DELETE"})}catch(err){alert(err instanceof Error?err.message:"Unable to save category photo")}finally{setCategorySaving("")}}
 async function removeCategoryPhoto(name:string){if(!confirm(`Remove the photo for ${name}?`))return;setCategorySaving(name);try{const key=categoryPhotos[name],save=await fetch("/api/categories",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({name,imageKey:null})}),saved=await save.json();if(!save.ok)throw new Error(saved.error||"Unable to remove category photo");if(key)await fetch(`/api/product-images?key=${encodeURIComponent(key)}`,{method:"DELETE"});setCategoryPhotos(current=>{const next={...current};delete next[name];return next})}catch(err){alert(err instanceof Error?err.message:"Unable to remove category photo")}finally{setCategorySaving("")}}
 async function saveMakingVideo(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setVideoSaving(true);setVideoError("");let uploadedKey="";try{const form=new FormData(e.currentTarget),file=form.get("video");if(!(file instanceof File)||!file.size)throw new Error("Choose a video first");const uploadForm=new FormData();uploadForm.set("video",file);const upload=await fetch("/api/video-files",{method:"POST",body:uploadForm}),uploaded=await upload.json();if(!upload.ok)throw new Error(uploaded.error||"Video upload failed");uploadedKey=String(uploaded.key);const save=await fetch("/api/videos",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify({title:form.get("title"),description:form.get("description"),videoKey:uploadedKey})}),saved=await save.json();if(!save.ok)throw new Error(saved.error||"Unable to save video");setMakingVideos(current=>[saved.video,...current]);e.currentTarget.reset()}catch(err){if(uploadedKey)await fetch(`/api/video-files?key=${encodeURIComponent(uploadedKey)}`,{method:"DELETE"});setVideoError(err instanceof Error?err.message:"Unable to upload video")}finally{setVideoSaving(false)}}
 async function removeMakingVideo(video:MakingVideo){if(!confirm(`Remove ${video.title}?`))return;const response=await fetch(`/api/videos?id=${encodeURIComponent(video.id)}`,{method:"DELETE"}),data=await response.json();if(!response.ok)return alert(data.error||"Unable to remove video");await fetch(`/api/video-files?key=${encodeURIComponent(video.videoKey)}`,{method:"DELETE"});setMakingVideos(current=>current.filter(item=>item.id!==video.id))}
 async function saveProduct(e:React.FormEvent<HTMLFormElement>){e.preventDefault();setSaving(true);setError("");try{const f=new FormData(e.currentTarget),uploaded=await Promise.all(pendingFiles.map(async({file})=>{const form=new FormData();form.set("image",file);const r=await fetch("/api/product-images",{method:"POST",body:form}),d=await r.json();if(!r.ok)throw new Error(d.error||"Image upload failed");return String(d.key)})),imageKeys=[...retainedKeys,...uploaded],p:Product={id:editing?.id||Date.now(),name:String(f.get("name")),category:String(f.get("category")),price:Number(f.get("price")),stock:Number(f.get("stock")),material:String(f.get("material")),color:String(f.get("color")),description:String(f.get("description")),imageKey:imageKeys[0]||null,imageKeys};const r=await fetch("/api/products",{method:"POST",headers:{"Content-Type":"application/json"},body:JSON.stringify(p)}),d=await r.json();if(!r.ok)throw new Error(d.error||"Unable to save product");setProducts(c=>[...c.filter(x=>x.id!==p.id),p]);setEditing(null)}catch(err){setError(err instanceof Error?err.message:"Unable to save product")}finally{setSaving(false)}}
 async function deleteProduct(p:Product){if(!confirm(`Delete ${p.name}?`))return;const r=await fetch(`/api/products?id=${p.id}`,{method:"DELETE"}),d=await r.json();if(!r.ok)return alert(d.error||"Unable to delete product");setProducts(c=>c.filter(x=>x.id!==p.id))}
 async function updateOrder(e:React.FormEvent<HTMLFormElement>){e.preventDefault();const f=new FormData(e.currentTarget),payload=Object.fromEntries(f.entries()),r=await fetch("/api/orders",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({...payload,id:selectedOrder.id})}),d=await r.json();if(!r.ok)return alert(d.error||"Unable to update order");setOrders(c=>c.map(o=>o.id===selectedOrder.id?{...o,...payload}:o));setSelectedOrder(null)}
 async function removeOrder(id:string){if(!confirm(`Remove order ${id}? This cannot be undone.`))return;const r=await fetch(`/api/orders?id=${encodeURIComponent(id)}`,{method:"DELETE"});if(r.ok)setOrders(c=>c.filter(o=>o.id!==id))}
 async function updateQuote(id:string,status:string,ownerNote:string){const r=await fetch("/api/quotes",{method:"PATCH",headers:{"Content-Type":"application/json"},body:JSON.stringify({id,status,ownerNote})});if(r.ok)setQuotes(c=>c.map(q=>q.id===id?{...q,status,ownerNote}:q))}
 function printInvoice(order:any){const items=order.items.map((i:any)=>`<tr><td>${i.name}<br><small>${i.color}</small></td><td>${i.quantity}</td><td>${money(i.price)}</td><td>${money(i.price*i.quantity)}</td></tr>`).join("");const w=window.open("","_blank");w?.document.write(`<!doctype html><title>Invoice ${order.id}</title><style>body{font:14px Arial;color:#222;padding:40px;max-width:850px;margin:auto}header{display:flex;justify-content:space-between;border-bottom:3px solid #222;padding-bottom:20px}h1{letter-spacing:.12em}table{width:100%;border-collapse:collapse;margin:30px 0}th,td{text-align:left;padding:12px;border-bottom:1px solid #ddd}.totals{margin-left:auto;width:280px}.totals p{display:flex;justify-content:space-between}.total{font-size:18px;font-weight:bold;border-top:2px solid #222;padding-top:12px}@media print{button{display:none}}</style><header><div><h1>THREE D HOUSE</h1><p>Designed in Layers. Made for Life.</p></div><div><b>TAX INVOICE</b><p>${order.id}<br>${new Date(order.createdAt).toLocaleDateString("en-IN")}</p></div></header><section><h3>Bill & ship to</h3><p><b>${order.customerName}</b><br>${order.phone}${order.email?` · ${order.email}`:""}<br>${order.address}, ${order.city}, ${order.state} – ${order.pincode}</p></section><table><thead><tr><th>Item</th><th>Qty</th><th>Rate</th><th>Amount</th></tr></thead><tbody>${items}</tbody></table><div class="totals"><p><span>Subtotal</span><b>${money(order.subtotal)}</b></p><p><span>Shipping</span><b>${money(order.shipping)}</b></p><p class="total"><span>Total</span><b>${money(order.total)}</b></p></div><p>Payment: ${order.paymentMethod==="razorpay"?"Online · Paid":"Cash on Delivery"}</p><button onclick="window.print()">Print / Save PDF</button>`);w?.document.close()}
 const newProduct:Product={id:0,name:"",category:"Bathroom",price:0,stock:0,material:"PETG",color:"",description:"",imageKey:null,imageKeys:[]};
 return <main className="admin-shell">
  <aside className="admin-side"><div className="admin-logo"><img src="/three-d-house-logo.png" alt=""/><b>THREE D HOUSE<br/>ADMIN</b></div><nav>{menu.map(([Icon,n])=><button key={n} className={tab===n?"active":""} onClick={()=>setTab(n)}><Icon size={15}/> &nbsp;{n}</button>)}</nav><a href={signOut} target="_top" className="admin-signout"><LogOut size={14}/> Sign out</a></aside>
  <section className="admin-main"><header className="admin-top"><div><h1>{tab}</h1><p>Welcome back, {owner}. Manage your complete storefront.</p></div>{tab==="Products"&&<button className="admin-btn" onClick={()=>openProduct(newProduct)}><Plus size={15}/> Add product</button>}</header>
   <div className="stats"><article className="stat"><small>Recorded sales</small><b>{money(sales)}</b></article><article className="stat"><small>Open orders</small><b>{openOrders}</b></article><article className="stat"><small>Live products</small><b>{products.length}</b></article><article className="stat"><small>New quotes</small><b>{quotes.filter(q=>q.status==="new").length}</b></article></div>
   {tab==="Overview"&&<div className="admin-dashboard-grid"><section className="admin-card"><div className="admin-card-head"><div><h2>Latest orders</h2><small>Your most recent customer activity.</small></div><ShoppingCart/></div>{orders.slice(0,5).map(o=><button className="activity-row" key={o.id} onClick={()=>{setTab("Orders");setSelectedOrder(o)}}><span><b>{o.id}</b><small>{o.customerName} · {new Date(o.createdAt).toLocaleDateString("en-IN")}</small></span><strong>{money(o.total)}</strong></button>)}{!orders.length&&<Empty text="No orders yet"/>}</section><section className="admin-card"><div className="admin-card-head"><div><h2>Store health</h2><small>Items that need your attention.</small></div><Box/></div><div className="health-list"><p><span>Low-stock products</span><b>{products.filter(p=>p.stock<5).length}</b></p><p><span>Orders awaiting acceptance</span><b>{orders.filter(o=>o.orderStatus==="new").length}</b></p><p><span>Quotes awaiting review</span><b>{quotes.filter(q=>q.status==="new").length}</b></p></div></section></div>}
   {tab==="Products"&&<section className="admin-card"><div className="admin-card-head"><div><h2>Product catalogue</h2><small>Images, colours, prices and inventory.</small></div><Box/></div><div className="table-scroll"><table><thead><tr><th>Images</th><th>Product</th><th>Category</th><th>Price</th><th>Inventory</th><th>Actions</th></tr></thead><tbody>{products.map(p=><tr key={p.id}><td>{keysFor(p).length?<div className="admin-thumb-wrap"><img className="admin-product-thumb" src={imageUrl(keysFor(p)[0])} alt=""/>{keysFor(p).length>1&&<b>+{keysFor(p).length-1}</b>}</div>:<span className="admin-no-image"><ImagePlus size={16}/></span>}</td><td><b>{p.name}</b><br/><small>{p.material} · {p.color||"Standard"}</small></td><td>{p.category}</td><td>{money(p.price)}</td><td><span className={p.stock<5?"stock low":"stock"}>{p.stock} in stock</span></td><td><button className="edit-btn" onClick={()=>openProduct(p)}>Edit</button> <button className="icon-danger" onClick={()=>deleteProduct(p)} aria-label="Delete"><Trash2 size={14}/></button></td></tr>)}</tbody></table></div></section>}
   {tab==="Category Photos"&&<section className="admin-card"><div className="admin-card-head"><div><h2>Explore the Collection photos</h2><small>Upload one cover photo for every storefront category.</small></div><ImagePlus/></div><div className="category-photo-admin-grid">{categoryNames.map(name=><article className="category-photo-admin" key={name}>{categoryPhotos[name]?<img src={imageUrl(categoryPhotos[name])} alt={`${name} category`}/>:<div className="category-photo-empty"><ImagePlus/><span>No photo added</span></div>}<div><b>{name}</b><small>{categorySaving===name?"Uploading…":"JPG, PNG or WebP · maximum 8 MB"}</small></div><label className="edit-btn category-upload">{categoryPhotos[name]?"Replace photo":"Add photo"}<input type="file" accept="image/jpeg,image/png,image/webp" disabled={Boolean(categorySaving)} onChange={e=>{const file=e.target.files?.[0];if(file)saveCategoryPhoto(name,file);e.target.value=""}}/></label>{categoryPhotos[name]&&<button className="icon-danger" disabled={Boolean(categorySaving)} onClick={()=>removeCategoryPhoto(name)}><Trash2 size={14}/> Remove</button>}</article>)}</div></section>}
   {tab==="Making Videos"&&<section className="admin-video-layout"><form className="admin-card video-upload-form" onSubmit={saveMakingVideo}><div className="admin-card-head"><div><h2>Add a making video</h2><small>Show customers how a THREE D HOUSE product is printed and finished.</small></div><Upload/></div><label>Video title<input name="title" required placeholder="e.g. Printing the Ripple Soap Dish"/></label><label>Description<textarea name="description" placeholder="Briefly explain what customers are watching"/></label><label className="video-file-picker"><Film/><b>Choose video</b><small>MP4, WebM or MOV · maximum 80 MB</small><input name="video" type="file" accept="video/mp4,video/webm,video/quicktime" required/></label>{videoError&&<p className="form-error">{videoError}</p>}<button className="admin-btn" disabled={videoSaving}>{videoSaving?"Uploading video…":"Upload & publish video"}</button></form><section className="admin-card"><div className="admin-card-head"><div><h2>Published videos</h2><small>These appear in the “Made Layer by Layer” storefront section.</small></div><Film/></div>{makingVideos.length?<div className="admin-video-grid">{makingVideos.map(video=><article key={video.id}><video controls preload="metadata" src={`/api/video-files?key=${encodeURIComponent(video.videoKey)}`}/><div><b>{video.title}</b>{video.description&&<p>{video.description}</p>}<small>{new Date(video.createdAt).toLocaleDateString("en-IN")}</small><button className="icon-danger" onClick={()=>removeMakingVideo(video)}><Trash2 size={14}/> Remove</button></div></article>)}</div>:<Empty text="No making videos uploaded yet"/>}</section></section>}
   {tab==="Orders"&&<section className="admin-card"><div className="admin-card-head"><div><h2>Customer orders</h2><small>See exactly what was ordered, then accept, fulfil, track and invoice it.</small></div><Truck/></div>{orders.length?<div className="table-scroll"><table><thead><tr><th>Order</th><th>Products ordered</th><th>Customer</th><th>Payment</th><th>Total</th><th>Status</th><th>Actions</th></tr></thead><tbody>{orders.map(o=><tr key={o.id}><td><b>{o.id}</b><br/><small>{new Date(o.createdAt).toLocaleDateString("en-IN")}</small></td><td><div className="order-product-list">{o.items.map((item:any,index:number)=><div className="order-product-summary" key={`${item.productId}-${item.color}-${index}`}>{item.imageKey?<img src={imageUrl(item.imageKey)} alt={item.name}/>:<span className="order-product-placeholder"><ImagePlus size={16}/></span>}<span><b>{item.name}</b><small>{item.color||"Standard"} · Qty {item.quantity}</small></span></div>)}</div></td><td><b>{o.customerName}</b><br/><small>{o.phone} · {o.city}</small></td><td>{o.paymentMethod==="razorpay"?"Online · Paid":"COD"}</td><td>{money(o.total)}</td><td><span className={`order-state ${o.orderStatus}`}>{o.orderStatus}</span>{o.trackingNumber&&<small className="tracking-mini">{o.courier} · {o.trackingNumber}</small>}</td><td><button className="edit-btn" onClick={()=>setSelectedOrder(o)}>Manage</button> <button className="edit-btn" onClick={()=>printInvoice(o)}><Printer size={13}/> Invoice</button> <button className="icon-danger" onClick={()=>removeOrder(o.id)}><Trash2 size={14}/></button></td></tr>)}</tbody></table></div>:<Empty text="No orders yet"/>}</section>}
   {tab==="Custom Quotes"&&<section className="admin-card"><div className="admin-card-head"><div><h2>Custom print requests</h2><small>Review customer ideas and record quote progress.</small></div><ClipboardList/></div>{quotes.length?<div className="quote-grid">{quotes.map(q=><article className="quote-card" key={q.id}><div><span className="order-state">{q.status}</span><small>{q.id} · {new Date(q.createdAt).toLocaleDateString("en-IN")}</small></div><h3>{q.projectType}</h3><p>{q.description}</p><small><b>{q.customerName}</b> · {q.phone}{q.email?` · ${q.email}`:""}<br/>Quantity: {q.quantity}</small><label>Status<select value={q.status} onChange={e=>updateQuote(q.id,e.target.value,q.ownerNote)}>{["new","reviewing","quoted","approved","closed"].map(s=><option key={s}>{s}</option>)}</select></label><label>Owner note<textarea defaultValue={q.ownerNote} onBlur={e=>updateQuote(q.id,q.status,e.target.value)}/></label></article>)}</div>:<Empty text="No custom quote requests yet"/>}</section>}
   {tab==="Customers"&&<section className="admin-card"><div className="admin-card-head"><div><h2>Customers</h2><small>Built automatically from placed orders.</small></div><Users/></div>{customers.length?<div className="table-scroll"><table><thead><tr><th>Customer</th><th>Contact</th><th>Location</th><th>Orders</th><th>Total spent</th></tr></thead><tbody>{customers.map((c:any)=><tr key={c.phone}><td><b>{c.customerName}</b></td><td>{c.phone}<br/><small>{c.email}</small></td><td>{c.city}, {c.state}</td><td>{orders.filter(o=>o.phone===c.phone).length}</td><td>{money(orders.filter(o=>o.phone===c.phone&&o.orderStatus!=="cancelled").reduce((s,o)=>s+o.total,0))}</td></tr>)}</tbody></table></div>:<Empty text="Customers will appear after their first order"/>}</section>}
   {tab==="Analytics"&&<section className="admin-dashboard-grid"><article className="admin-card metric-card"><small>Average order value</small><b>{money(orders.length?sales/orders.length:0)}</b><p>Based on all non-cancelled orders.</p></article><article className="admin-card metric-card"><small>Units ordered</small><b>{orders.reduce((s,o)=>s+o.items.reduce((a:number,i:any)=>a+i.quantity,0),0)}</b><p>Total items across placed orders.</p></article><article className="admin-card metric-card"><small>Online payments</small><b>{orders.filter(o=>o.paymentMethod==="razorpay").length}</b><p>Successfully verified Razorpay orders.</p></article><article className="admin-card metric-card"><small>Completed orders</small><b>{orders.filter(o=>o.orderStatus==="completed").length}</b><p>Orders marked successfully delivered.</p></article></section>}
  </section>
  {editing&&<div className="admin-modal"><form className="admin-form" onSubmit={saveProduct}><div className="admin-card-head"><h2>{editing.id?"Edit product":"Add product"}</h2><button type="button" onClick={()=>setEditing(null)}><X/></button></div><div className="form-grid"><label className="wide multi-image-upload"><span>Product images</span><input type="file" multiple accept="image/jpeg,image/png,image/webp" onChange={chooseImages}/><div className="multi-image-box"><ImagePlus/><b>Choose multiple product images</b><small>JPG, PNG or WebP · maximum 8 MB each</small></div></label>{(retainedKeys.length>0||pendingFiles.length>0)&&<div className="wide image-previews">{retainedKeys.map((key,i)=><div key={key}><img src={imageUrl(key)} alt={`Image ${i+1}`}/><button type="button" onClick={()=>setRetainedKeys(c=>c.filter(k=>k!==key))}><X/> Remove</button></div>)}{pendingFiles.map((item,i)=><div key={item.url}><img src={item.url} alt={`New image ${i+1}`}/><button type="button" onClick={()=>removePending(i)}><X/> Remove</button></div>)}</div>}<label className="wide">Product name<input name="name" defaultValue={editing.name} required/></label><label>Category<select name="category" defaultValue={editing.category}>{["Bathroom","Kitchen","Home Organization","Desk & Office","Planters & Décor","Personalized Gifts"].map(x=><option key={x}>{x}</option>)}</select></label><label>Material<select name="material" defaultValue={editing.material}><option>PETG</option><option>PLA+</option><option>PLA</option></select></label><label>Price (₹)<input name="price" type="number" min="1" defaultValue={editing.price} required/></label><label>Stock<input name="stock" type="number" min="0" defaultValue={editing.stock} required/></label><label className="wide">Colours (comma separated)<input name="color" defaultValue={editing.color} placeholder="Black, White, Blue"/></label><label className="wide">Description<textarea name="description" defaultValue={editing.description} required/></label></div>{error&&<p className="form-error">{error}</p>}<div className="form-actions"><button type="button" onClick={()=>setEditing(null)}>Cancel</button><button className="save" disabled={saving}>{saving?"Uploading & saving…":"Save product"}</button></div></form></div>}
  {selectedOrder&&<div className="admin-modal"><form className="admin-form order-form" onSubmit={updateOrder}><div className="admin-card-head"><div><h2>Manage {selectedOrder.id}</h2><small>{selectedOrder.customerName} · {selectedOrder.phone}</small></div><button type="button" onClick={()=>setSelectedOrder(null)}><X/></button></div><div className="order-customer"><b>Delivery address</b><p>{selectedOrder.address}, {selectedOrder.city}, {selectedOrder.state} – {selectedOrder.pincode}</p></div><div className="order-items">{selectedOrder.items.map((i:any,index:number)=><div className="order-item-detail" key={`${i.productId}-${i.color}-${index}`}>{i.imageKey?<img src={imageUrl(i.imageKey)} alt={i.name}/>:<span className="order-product-placeholder"><ImagePlus size={20}/></span>}<span><b>{i.name}</b><small>{i.color||"Standard"} · Quantity {i.quantity}</small></span><strong>{money(i.price*i.quantity)}</strong></div>)}</div><div className="form-grid"><label>Status<select name="status" defaultValue={selectedOrder.orderStatus}>{statuses.map(s=><option key={s}>{s}</option>)}</select></label><label>Courier<input name="courier" defaultValue={selectedOrder.courier} placeholder="e.g. Delhivery"/></label><label>Tracking number<input name="trackingNumber" defaultValue={selectedOrder.trackingNumber}/></label><label>Tracking URL<input name="trackingUrl" type="url" defaultValue={selectedOrder.trackingUrl}/></label><label className="wide">Private owner note<textarea name="ownerNote" defaultValue={selectedOrder.ownerNote}/></label></div><div className="form-actions"><button type="button" onClick={()=>printInvoice(selectedOrder)}><Download size={14}/> Invoice</button><button className="save">Save order</button></div></form></div>}
 </main>
}
function Empty({text}:{text:string}){return <div className="admin-empty"><Box/><h3>{text}</h3></div>}
